// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz-H9JjzVAoaAlSe531g-OnfUPh46MyAc',
    appId: '1:337492182765:web:2ca01b33516244f812aee4',
    messagingSenderId: '337492182765',
    projectId: 'inspecta-68798',
    authDomain: 'inspecta-68798.firebaseapp.com',
    storageBucket: 'inspecta-68798.firebasestorage.app',
    measurementId: 'G-5KL4GRCXY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKTkdyYmTSskhhzhaRmQYMcR2sAL7qTBU',
    appId: '1:337492182765:android:adcf59352b3bf01512aee4',
    messagingSenderId: '337492182765',
    projectId: 'inspecta-68798',
    storageBucket: 'inspecta-68798.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Ii4CWR5cpcehelYbz5ARv9CeQggKyow',
    appId: '1:337492182765:ios:eb9e7f72d0fb9e5312aee4',
    messagingSenderId: '337492182765',
    projectId: 'inspecta-68798',
    storageBucket: 'inspecta-68798.firebasestorage.app',
    iosBundleId: 'com.example.inspecta',
  );
}
